// Generated by gencpp from file pick_and_place/Grasp.msg
// DO NOT EDIT!


#ifndef PICK_AND_PLACE_MESSAGE_GRASP_H
#define PICK_AND_PLACE_MESSAGE_GRASP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace pick_and_place
{
template <class ContainerAllocator>
struct Grasp_
{
  typedef Grasp_<ContainerAllocator> Type;

  Grasp_()
    : pose()
    , width(0.0)
    , quality(0.0)  {
    }
  Grasp_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , width(0.0)
    , quality(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _width_type;
  _width_type width;

   typedef float _quality_type;
  _quality_type quality;





  typedef boost::shared_ptr< ::pick_and_place::Grasp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_and_place::Grasp_<ContainerAllocator> const> ConstPtr;

}; // struct Grasp_

typedef ::pick_and_place::Grasp_<std::allocator<void> > Grasp;

typedef boost::shared_ptr< ::pick_and_place::Grasp > GraspPtr;
typedef boost::shared_ptr< ::pick_and_place::Grasp const> GraspConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_and_place::Grasp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_and_place::Grasp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_and_place::Grasp_<ContainerAllocator1> & lhs, const ::pick_and_place::Grasp_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.width == rhs.width &&
    lhs.quality == rhs.quality;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_and_place::Grasp_<ContainerAllocator1> & lhs, const ::pick_and_place::Grasp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_and_place

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pick_and_place::Grasp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_and_place::Grasp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_and_place::Grasp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_and_place::Grasp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_and_place::Grasp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_and_place::Grasp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_and_place::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffb74d75fb92764666a6fb85638db3e0";
  }

  static const char* value(const ::pick_and_place::Grasp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffb74d75fb927646ULL;
  static const uint64_t static_value2 = 0x66a6fb85638db3e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_and_place::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_and_place/Grasp";
  }

  static const char* value(const ::pick_and_place::Grasp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_and_place::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"float32 width\n"
"float32 quality\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pick_and_place::Grasp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_and_place::Grasp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.width);
      stream.next(m.quality);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Grasp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_and_place::Grasp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_and_place::Grasp_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "quality: ";
    Printer<float>::stream(s, indent + "  ", v.quality);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_AND_PLACE_MESSAGE_GRASP_H
